version: "3.8"
services:
  user:
    build: ./services/user
    ports: 
      - 4001:4001
  employee:
    build: ./services/employee
    ports: 
      - 4002:4002
  project:
    build: ./services/project
    ports: 
      - 4003:4003
  mongodb: 
    image: "mongo:4.0-xenial"
    ports: 
      - 27017:27017