export const API_ROUTES = {
  AUTH: process.env.NEXT_PUBLIC_BACKEND_URL_AUTH,
  PROJECT: process.env.NEXT_PUBLIC_BACKEND_URL_PROJECT,
  EMPLOYEE: process.env.NEXT_PUBLIC_BACKEND_URL_EMPLOYEE,
  CHAT: process.env.NEXT_PUBLIC_BACKEND_URL_CHAT,
  CLIENT_DEALS: process.env.NEXT_PUBLIC_BACKEND_URL_CLIENT_AND_DEALS,
  SUBSCRIPTION: process.env.NEXT_PUBLIC_BACKEND_URL_SUBSCRIPTION,
};
