apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: clients-deals
  name: clients-deals
spec:
  ports:
    - name: "4005"
      port: 4005
      targetPort: 4005
  selector:
    io.kompose.service: clients-deals
